#!/bin/bash
Put a container in the background.
Attach to a background container to bring it to the foreground.
Restart a stopped container.
The distinction between foreground and background containers is arbitrary.
From Docker's point of view, all containers are the same.
All containers run the same way, whether there is a client attached to them or not.
It is always possible to detach from a container, and to reattach to a container.
Analogy: attaching to a container is like plugging a keyboard and screen to a physical server.

 docker attach <containerID>
 docker logs --tail 1 --follow <containerID>
 docker start <yourContainerID>
 docker attach <yourContainerID>

